server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mybatis-demo
    username: postgres
    password: Admin@123

mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.mybatisdemo
